//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.31 at 02:45:59 PM EDT 
//


package com.cfinkel.reports.generatedbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.cfinkel.reports.generatedbeans.Control;
import com.cfinkel.reports.generatedbeans.ControlElement;
import com.cfinkel.reports.generatedbeans.Datatype;
import com.cfinkel.reports.generatedbeans.GeneratedQueryElement;
import com.cfinkel.reports.generatedbeans.InputElement;
import com.cfinkel.reports.generatedbeans.PreparedQueryElement;


/**
 * <p>Java class for input element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="input">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;extension base="{http://www.cfinkel.com/report}abstract-input">
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.cfinkel.com/report}control" minOccurs="0"/>
 *           &lt;choice minOccurs="0">
 *             &lt;element ref="{http://www.cfinkel.com/report}query"/>
 *             &lt;element ref="{http://www.cfinkel.com/report}generated-query"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *         &lt;attribute name="control" use="required" type="{http://www.cfinkel.com/report}control" />
 *         &lt;attribute name="datatype" use="required" type="{http://www.cfinkel.com/report}datatype" />
 *         &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="values" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;/extension>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "controlAndQueryOrGeneratedQuery"
})
@XmlRootElement(name = "input")
public class BaseInputElement
    extends InputElement
{

    @XmlElements({
        @XmlElement(name = "generated-query", namespace = "http://www.cfinkel.com/report", type = GeneratedQueryElement.class),
        @XmlElement(name = "control", namespace = "http://www.cfinkel.com/report", type = ControlElement.class),
        @XmlElement(name = "query", namespace = "http://www.cfinkel.com/report", type = PreparedQueryElement.class)
    })
    protected List<Object> controlAndQueryOrGeneratedQuery;
    @XmlAttribute(required = true)
    protected Control control;
    @XmlAttribute(required = true)
    protected Datatype datatype;
    @XmlAttribute(name = "default")
    protected String _default;
    @XmlAttribute(required = true)
    protected String description;
    @XmlAttribute
    protected String values;

    /**
     * Gets the value of the controlAndQueryOrGeneratedQuery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlAndQueryOrGeneratedQuery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControlAndQueryOrGeneratedQuery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeneratedQueryElement }
     * {@link ControlElement }
     * {@link PreparedQueryElement }
     * 
     * 
     */
    public List<Object> getControlAndQueryOrGeneratedQuery() {
        if (controlAndQueryOrGeneratedQuery == null) {
            controlAndQueryOrGeneratedQuery = new ArrayList<Object>();
        }
        return this.controlAndQueryOrGeneratedQuery;
    }

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link Control }
     *     
     */
    public Control getControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link Control }
     *     
     */
    public void setControl(Control value) {
        this.control = value;
    }

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link Datatype }
     *     
     */
    public Datatype getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datatype }
     *     
     */
    public void setDatatype(Datatype value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefault(String value) {
        this._default = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValues(String value) {
        this.values = value;
    }

}
