//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.31 at 02:45:59 PM EDT 
//


package com.cfinkel.reports.generatedbeans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for chart.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="chart">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="table"/>
 *     &lt;enumeration value="bar"/>
 *     &lt;enumeration value="pie"/>
 *     &lt;enumeration value="xy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum Chart {

    @XmlEnumValue("bar")
    BAR("bar"),
    @XmlEnumValue("pie")
    PIE("pie"),
    @XmlEnumValue("table")
    TABLE("table"),
    @XmlEnumValue("xy")
    XY("xy");
    private final String value;

    Chart(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Chart fromValue(String v) {
        for (Chart c: Chart.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
