//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.31 at 02:45:59 PM EDT 
//


package com.cfinkel.reports.generatedbeans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for control.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="control">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="radio"/>
 *     &lt;enumeration value="dropdown"/>
 *     &lt;enumeration value="text"/>
 *     &lt;enumeration value="listbox"/>
 *     &lt;enumeration value="checkbox"/>
 *     &lt;enumeration value="textarea"/>
 *     &lt;enumeration value="date"/>
 *     &lt;enumeration value="datetime"/>
 *     &lt;enumeration value="time"/>
 *     &lt;enumeration value="hidden"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum Control {

    @XmlEnumValue("checkbox")
    CHECKBOX("checkbox"),
    @XmlEnumValue("date")
    DATE("date"),
    @XmlEnumValue("datetime")
    DATETIME("datetime"),
    @XmlEnumValue("dropdown")
    DROPDOWN("dropdown"),
    @XmlEnumValue("hidden")
    HIDDEN("hidden"),
    @XmlEnumValue("listbox")
    LISTBOX("listbox"),
    @XmlEnumValue("radio")
    RADIO("radio"),
    @XmlEnumValue("text")
    TEXT("text"),
    @XmlEnumValue("textarea")
    TEXTAREA("textarea"),
    @XmlEnumValue("time")
    TIME("time");
    private final String value;

    Control(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Control fromValue(String v) {
        for (Control c: Control.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
