//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.31 at 02:45:59 PM EDT 
//


package com.cfinkel.reports.generatedbeans;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.cfinkel.reports.generatedbeans.ListboxElement;
import com.cfinkel.reports.generatedbeans.RadioElement;
import com.cfinkel.reports.generatedbeans.TextareaElement;


/**
 * <p>Java class for control element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="control">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice>
 *           &lt;element ref="{http://www.cfinkel.com/report}listbox"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}radio"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}textarea"/>
 *         &lt;/choice>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listbox",
    "radio",
    "textarea"
})
@XmlRootElement(name = "control")
public class ControlElement {

    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected ListboxElement listbox;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected RadioElement radio;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected TextareaElement textarea;

    /**
     * Gets the value of the listbox property.
     * 
     * @return
     *     possible object is
     *     {@link ListboxElement }
     *     
     */
    public ListboxElement getListbox() {
        return listbox;
    }

    /**
     * Sets the value of the listbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListboxElement }
     *     
     */
    public void setListbox(ListboxElement value) {
        this.listbox = value;
    }

    /**
     * Gets the value of the radio property.
     * 
     * @return
     *     possible object is
     *     {@link RadioElement }
     *     
     */
    public RadioElement getRadio() {
        return radio;
    }

    /**
     * Sets the value of the radio property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadioElement }
     *     
     */
    public void setRadio(RadioElement value) {
        this.radio = value;
    }

    /**
     * Gets the value of the textarea property.
     * 
     * @return
     *     possible object is
     *     {@link TextareaElement }
     *     
     */
    public TextareaElement getTextarea() {
        return textarea;
    }

    /**
     * Sets the value of the textarea property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextareaElement }
     *     
     */
    public void setTextarea(TextareaElement value) {
        this.textarea = value;
    }

}
