//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.31 at 02:45:59 PM EDT 
//


package com.cfinkel.reports.generatedbeans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.cfinkel.reports.generatedbeans.AccessElement;
import com.cfinkel.reports.generatedbeans.BaseInputElement;
import com.cfinkel.reports.generatedbeans.ChartElement;
import com.cfinkel.reports.generatedbeans.ControlElement;
import com.cfinkel.reports.generatedbeans.DependentInputElement;
import com.cfinkel.reports.generatedbeans.DrillDownElement;
import com.cfinkel.reports.generatedbeans.FormatElement;
import com.cfinkel.reports.generatedbeans.GeneratedQueryElement;
import com.cfinkel.reports.generatedbeans.InputParamElement;
import com.cfinkel.reports.generatedbeans.ListboxElement;
import com.cfinkel.reports.generatedbeans.OutputElement;
import com.cfinkel.reports.generatedbeans.PreparedQueryElement;
import com.cfinkel.reports.generatedbeans.RadioElement;
import com.cfinkel.reports.generatedbeans.ReportElement;
import com.cfinkel.reports.generatedbeans.TextareaElement;
import com.cfinkel.reports.generatedbeans.WhenElement;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cfinkel.reports.generatedbeans package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Role_QNAME = new QName("http://www.cfinkel.com/report", "role");
    private final static QName _Text_QNAME = new QName("http://www.cfinkel.com/report", "text");
    private final static QName _Backlink_QNAME = new QName("http://www.cfinkel.com/report", "backlink");
    private final static QName _QueryRef_QNAME = new QName("http://www.cfinkel.com/report", "query-ref");
    private final static QName _InputRef_QNAME = new QName("http://www.cfinkel.com/report", "input-ref");
    private final static QName _Group_QNAME = new QName("http://www.cfinkel.com/report", "group");
    private final static QName _Sql_QNAME = new QName("http://www.cfinkel.com/report", "sql");
    private final static QName _Total_QNAME = new QName("http://www.cfinkel.com/report", "total");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cfinkel.reports.generatedbeans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccessElement }
     * 
     */
    public AccessElement createAccessElement() {
        return new AccessElement();
    }

    /**
     * Create an instance of {@link InputParamElement }
     * 
     */
    public InputParamElement createInputParamElement() {
        return new InputParamElement();
    }

    /**
     * Create an instance of {@link ReportElement }
     * 
     */
    public ReportElement createReportElement() {
        return new ReportElement();
    }

    /**
     * Create an instance of {@link TextareaElement }
     * 
     */
    public TextareaElement createTextareaElement() {
        return new TextareaElement();
    }

    /**
     * Create an instance of {@link PreparedQueryElement }
     * 
     */
    public PreparedQueryElement createPreparedQueryElement() {
        return new PreparedQueryElement();
    }

    /**
     * Create an instance of {@link DrillDownElement }
     * 
     */
    public DrillDownElement createDrillDownElement() {
        return new DrillDownElement();
    }

    /**
     * Create an instance of {@link OutputElement }
     * 
     */
    public OutputElement createOutputElement() {
        return new OutputElement();
    }

    /**
     * Create an instance of {@link DependentInputElement }
     * 
     */
    public DependentInputElement createDependentInputElement() {
        return new DependentInputElement();
    }

    /**
     * Create an instance of {@link RadioElement }
     * 
     */
    public RadioElement createRadioElement() {
        return new RadioElement();
    }

    /**
     * Create an instance of {@link WhenElement }
     * 
     */
    public WhenElement createWhenElement() {
        return new WhenElement();
    }

    /**
     * Create an instance of {@link BaseInputElement }
     * 
     */
    public BaseInputElement createBaseInputElement() {
        return new BaseInputElement();
    }

    /**
     * Create an instance of {@link GeneratedQueryElement }
     * 
     */
    public GeneratedQueryElement createGeneratedQueryElement() {
        return new GeneratedQueryElement();
    }

    /**
     * Create an instance of {@link FormatElement }
     * 
     */
    public FormatElement createFormatElement() {
        return new FormatElement();
    }

    /**
     * Create an instance of {@link ControlElement }
     * 
     */
    public ControlElement createControlElement() {
        return new ControlElement();
    }

    /**
     * Create an instance of {@link ChartElement }
     * 
     */
    public ChartElement createChartElement() {
        return new ChartElement();
    }

    /**
     * Create an instance of {@link ListboxElement }
     * 
     */
    public ListboxElement createListboxElement() {
        return new ListboxElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cfinkel.com/report", name = "role")
    public JAXBElement<String> createRole(String value) {
        return new JAXBElement<String>(_Role_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cfinkel.com/report", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cfinkel.com/report", name = "backlink")
    public JAXBElement<String> createBacklink(String value) {
        return new JAXBElement<String>(_Backlink_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cfinkel.com/report", name = "query-ref")
    public JAXBElement<String> createQueryRef(String value) {
        return new JAXBElement<String>(_QueryRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cfinkel.com/report", name = "input-ref")
    public JAXBElement<String> createInputRef(String value) {
        return new JAXBElement<String>(_InputRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cfinkel.com/report", name = "group")
    public JAXBElement<String> createGroup(String value) {
        return new JAXBElement<String>(_Group_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cfinkel.com/report", name = "sql")
    public JAXBElement<String> createSql(String value) {
        return new JAXBElement<String>(_Sql_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cfinkel.com/report", name = "total")
    public JAXBElement<String> createTotal(String value) {
        return new JAXBElement<String>(_Total_QNAME, String.class, null, value);
    }

}
