//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.31 at 02:45:59 PM EDT 
//


package com.cfinkel.reports.generatedbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.cfinkel.reports.generatedbeans.ChartElement;
import com.cfinkel.reports.generatedbeans.DrillDownElement;
import com.cfinkel.reports.generatedbeans.FormatElement;
import com.cfinkel.reports.generatedbeans.GeneratedQueryElement;
import com.cfinkel.reports.generatedbeans.PreparedQueryElement;


/**
 * <p>Java class for output element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="output">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{http://www.cfinkel.com/report}format" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}total" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}drill-down" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}group" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;choice>
 *             &lt;element ref="{http://www.cfinkel.com/report}query"/>
 *             &lt;element ref="{http://www.cfinkel.com/report}generated-query"/>
 *             &lt;element ref="{http://www.cfinkel.com/report}query-ref"/>
 *           &lt;/choice>
 *           &lt;element ref="{http://www.cfinkel.com/report}chart" minOccurs="0"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}text" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="hideName" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *         &lt;attribute name="maxRowsForCache" type="{http://www.w3.org/2001/XMLSchema}int" default="-1" />
 *         &lt;attribute name="maxRowsForDisplayTag" type="{http://www.w3.org/2001/XMLSchema}int" default="-1" />
 *         &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="post-process-class" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="rowsPerPage" type="{http://www.w3.org/2001/XMLSchema}int" default="20" />
 *         &lt;attribute name="valueList" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "format",
    "total",
    "drillDown",
    "group",
    "query",
    "generatedQuery",
    "queryRef",
    "chart",
    "text"
})
@XmlRootElement(name = "output")
public class OutputElement {

    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected List<FormatElement> format;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected List<String> total;
    @XmlElement(name = "drill-down", namespace = "http://www.cfinkel.com/report")
    protected List<DrillDownElement> drillDown;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected List<String> group;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected PreparedQueryElement query;
    @XmlElement(name = "generated-query", namespace = "http://www.cfinkel.com/report")
    protected GeneratedQueryElement generatedQuery;
    @XmlElement(name = "query-ref", namespace = "http://www.cfinkel.com/report")
    protected String queryRef;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected ChartElement chart;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected String text;
    @XmlAttribute
    protected Boolean hideName;
    @XmlAttribute
    protected Integer maxRowsForCache;
    @XmlAttribute
    protected Integer maxRowsForDisplayTag;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(name = "post-process-class")
    protected String postProcessClass;
    @XmlAttribute
    protected Integer rowsPerPage;
    @XmlAttribute
    protected Boolean valueList;

    /**
     * Gets the value of the format property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the format property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormatElement }
     * 
     * 
     */
    public List<FormatElement> getFormat() {
        if (format == null) {
            format = new ArrayList<FormatElement>();
        }
        return this.format;
    }

    /**
     * Gets the value of the total property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the total property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTotal() {
        if (total == null) {
            total = new ArrayList<String>();
        }
        return this.total;
    }

    /**
     * Gets the value of the drillDown property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drillDown property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrillDown().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DrillDownElement }
     * 
     * 
     */
    public List<DrillDownElement> getDrillDown() {
        if (drillDown == null) {
            drillDown = new ArrayList<DrillDownElement>();
        }
        return this.drillDown;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGroup() {
        if (group == null) {
            group = new ArrayList<String>();
        }
        return this.group;
    }

    /**
     * Gets the value of the query property.
     * 
     * @return
     *     possible object is
     *     {@link PreparedQueryElement }
     *     
     */
    public PreparedQueryElement getQuery() {
        return query;
    }

    /**
     * Sets the value of the query property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreparedQueryElement }
     *     
     */
    public void setQuery(PreparedQueryElement value) {
        this.query = value;
    }

    /**
     * Gets the value of the generatedQuery property.
     * 
     * @return
     *     possible object is
     *     {@link GeneratedQueryElement }
     *     
     */
    public GeneratedQueryElement getGeneratedQuery() {
        return generatedQuery;
    }

    /**
     * Sets the value of the generatedQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneratedQueryElement }
     *     
     */
    public void setGeneratedQuery(GeneratedQueryElement value) {
        this.generatedQuery = value;
    }

    /**
     * Gets the value of the queryRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryRef() {
        return queryRef;
    }

    /**
     * Sets the value of the queryRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryRef(String value) {
        this.queryRef = value;
    }

    /**
     * Gets the value of the chart property.
     * 
     * @return
     *     possible object is
     *     {@link ChartElement }
     *     
     */
    public ChartElement getChart() {
        return chart;
    }

    /**
     * Sets the value of the chart property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartElement }
     *     
     */
    public void setChart(ChartElement value) {
        this.chart = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the hideName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHideName() {
        if (hideName == null) {
            return false;
        } else {
            return hideName;
        }
    }

    /**
     * Sets the value of the hideName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideName(Boolean value) {
        this.hideName = value;
    }

    /**
     * Gets the value of the maxRowsForCache property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxRowsForCache() {
        if (maxRowsForCache == null) {
            return -1;
        } else {
            return maxRowsForCache;
        }
    }

    /**
     * Sets the value of the maxRowsForCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxRowsForCache(Integer value) {
        this.maxRowsForCache = value;
    }

    /**
     * Gets the value of the maxRowsForDisplayTag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxRowsForDisplayTag() {
        if (maxRowsForDisplayTag == null) {
            return -1;
        } else {
            return maxRowsForDisplayTag;
        }
    }

    /**
     * Sets the value of the maxRowsForDisplayTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxRowsForDisplayTag(Integer value) {
        this.maxRowsForDisplayTag = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the postProcessClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostProcessClass() {
        return postProcessClass;
    }

    /**
     * Sets the value of the postProcessClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostProcessClass(String value) {
        this.postProcessClass = value;
    }

    /**
     * Gets the value of the rowsPerPage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getRowsPerPage() {
        if (rowsPerPage == null) {
            return  20;
        } else {
            return rowsPerPage;
        }
    }

    /**
     * Sets the value of the rowsPerPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRowsPerPage(Integer value) {
        this.rowsPerPage = value;
    }

    /**
     * Gets the value of the valueList property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isValueList() {
        if (valueList == null) {
            return false;
        } else {
            return valueList;
        }
    }

    /**
     * Sets the value of the valueList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValueList(Boolean value) {
        this.valueList = value;
    }

}
