//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.31 at 02:45:59 PM EDT 
//


package com.cfinkel.reports.generatedbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.cfinkel.reports.generatedbeans.QueryElement;


/**
 * <p>Java class for query element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="query">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;extension base="{http://www.cfinkel.com/report}abstract-query">
 *         &lt;sequence>
 *           &lt;element ref="{http://www.cfinkel.com/report}input-ref" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}sql"/>
 *         &lt;/sequence>
 *       &lt;/extension>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputRef",
    "sql"
})
@XmlRootElement(name = "query")
public class PreparedQueryElement
    extends QueryElement
{

    public void setInputRef(List<String> inputRef) {
        this.inputRef = inputRef;
    }

    @XmlElement(name = "input-ref", namespace = "http://www.cfinkel.com/report")
    protected List<String> inputRef;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected String sql;

    /**
     * Gets the value of the inputRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInputRef() {
        if (inputRef == null) {
            inputRef = new ArrayList<String>();
        }
        return this.inputRef;
    }

    /**
     * Gets the value of the sql property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSql() {
        return sql;
    }

    /**
     * Sets the value of the sql property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSql(String value) {
        this.sql = value;
    }

}
