//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.31 at 02:45:59 PM EDT 
//


package com.cfinkel.reports.generatedbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.cfinkel.reports.generatedbeans.AccessElement;
import com.cfinkel.reports.generatedbeans.BaseInputElement;
import com.cfinkel.reports.generatedbeans.OutputElement;
import com.cfinkel.reports.generatedbeans.PreparedQueryElement;


/**
 * <p>Java class for report element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="report">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{http://www.cfinkel.com/report}access"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}query" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}input" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}output" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.cfinkel.com/report}backlink" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="author" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="hideInputs" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *         &lt;attribute name="hideLinkToReport" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *         &lt;attribute name="hideLogin" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *         &lt;attribute name="revision" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="verticalInputs" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "access",
    "query",
    "input",
    "output",
    "backlink"
})
@XmlRootElement(name = "report")
public class ReportElement {

    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected AccessElement access;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected List<PreparedQueryElement> query;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected List<BaseInputElement> input;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected List<OutputElement> output;
    @XmlElement(namespace = "http://www.cfinkel.com/report")
    protected String backlink;
    @XmlAttribute
    protected String author;
    @XmlAttribute(required = true)
    protected String description;
    @XmlAttribute
    protected Boolean hideInputs;
    @XmlAttribute
    protected Boolean hideLinkToReport;
    @XmlAttribute
    protected Boolean hideLogin;
    @XmlAttribute
    protected String revision;
    @XmlAttribute(required = true)
    protected String title;
    @XmlAttribute
    protected Boolean verticalInputs;

    /**
     * Gets the value of the access property.
     * 
     * @return
     *     possible object is
     *     {@link AccessElement }
     *     
     */
    public AccessElement getAccess() {
        return access;
    }

    /**
     * Sets the value of the access property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessElement }
     *     
     */
    public void setAccess(AccessElement value) {
        this.access = value;
    }

    /**
     * Gets the value of the query property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the query property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PreparedQueryElement }
     * 
     * 
     */
    public List<PreparedQueryElement> getQuery() {
        if (query == null) {
            query = new ArrayList<PreparedQueryElement>();
        }
        return this.query;
    }

    /**
     * Gets the value of the input property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the input property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaseInputElement }
     * 
     * 
     */
    public List<BaseInputElement> getInput() {
        if (input == null) {
            input = new ArrayList<BaseInputElement>();
        }
        return this.input;
    }

    /**
     * Gets the value of the output property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the output property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutputElement }
     * 
     * 
     */
    public List<OutputElement> getOutput() {
        if (output == null) {
            output = new ArrayList<OutputElement>();
        }
        return this.output;
    }

    /**
     * Gets the value of the backlink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBacklink() {
        return backlink;
    }

    /**
     * Sets the value of the backlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBacklink(String value) {
        this.backlink = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the hideInputs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHideInputs() {
        if (hideInputs == null) {
            return false;
        } else {
            return hideInputs;
        }
    }

    /**
     * Sets the value of the hideInputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideInputs(Boolean value) {
        this.hideInputs = value;
    }

    /**
     * Gets the value of the hideLinkToReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHideLinkToReport() {
        if (hideLinkToReport == null) {
            return false;
        } else {
            return hideLinkToReport;
        }
    }

    /**
     * Sets the value of the hideLinkToReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideLinkToReport(Boolean value) {
        this.hideLinkToReport = value;
    }

    /**
     * Gets the value of the hideLogin property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHideLogin() {
        if (hideLogin == null) {
            return false;
        } else {
            return hideLogin;
        }
    }

    /**
     * Sets the value of the hideLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideLogin(Boolean value) {
        this.hideLogin = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the verticalInputs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVerticalInputs() {
        if (verticalInputs == null) {
            return false;
        } else {
            return verticalInputs;
        }
    }

    /**
     * Sets the value of the verticalInputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerticalInputs(Boolean value) {
        this.verticalInputs = value;
    }

}
